#=======================================================
# 標頭
# Header
#=======================================================

Title: Meta
Description: Used to indicate the time, authorship, or statistical data of a subject.

#=======================================================
# 設定
# Settings
#=======================================================

Type: Article
Relatives:
    - List

#=======================================================
# 基本樣式
# Definitions
#=======================================================

Example:
    Centered: true
    HTML: |
        <div class="[[ts-meta]]">
            <a class="item" href="#!">Terms of Use</a>
            <a class="item" href="#!">Privacy Policy</a>
            <a class="item" href="#!">Contact Us</a>
        </div>

Definitions:
    - Title: Variations
      Description:
      Sections:
          - Title: Secondary
            Anchor: Secondary
            Description: Makes the text color less conspicuous.
            Since: 4.0.0
            HTML: |
                <div class="ts-meta [[is-secondary]]">
                    <a class="item" href="#!">Amano Nozomi</a>
                    <a class="item" href="#!">Himukai Yuri</a>
                    <a class="item" href="#!">Narumi Haruka</a>
                </div>

          - Title: Aligns
            Anchor: Aligns
            Description: Change the alignment of the text.
            Since: 4.0.0
            Remove:
                - <div class="ts-space"></div>
            HTML: |
                <div class="ts-meta [[is-start-aligned]]">
                    <a class="item" href="#!">Start Aligned</a>
                    <a class="item" href="#!">Start Aligned</a>
                </div>
                <div class="ts-space"></div>
                <div class="ts-meta [[is-center-aligned]]">
                    <a class="item" href="#!">Center Aligned</a>
                    <a class="item" href="#!">Center Aligned</a>
                </div>
                <div class="ts-space"></div>
                <div class="ts-meta [[is-end-aligned]]">
                    <a class="item" href="#!">End Aligned</a>
                    <a class="item" href="#!">End Aligned</a>
                </div>

          - Title: Sizes
            Anchor: Sizes
            Description: Change the size of the meta.
            Since: 4.0.0
            Remove:
                - <div class="ts-space"></div>
            HTML: |
                <div class="ts-meta [[is-small]]">
                    <a class="item" href="#!">Tomotake Yoshino</a>
                    <a class="item" href="#!">Hitachi Mako</a>
                    <a class="item" href="#!">Murasame</a>
                </div>
                <div class="ts-space"></div>
                <div class="ts-meta">
                    <a class="item" href="#!">Tomotake Yoshino</a>
                    <a class="item" href="#!">Hitachi Mako</a>
                    <a class="item" href="#!">Murasame</a>
                </div>
                <div class="ts-space"></div>
                <div class="ts-meta [[is-large]]">
                    <a class="item" href="#!">Tomotake Yoshino</a>
                    <a class="item" href="#!">Hitachi Mako</a>
                    <a class="item" href="#!">Murasame</a>
                </div>

    - Title: Compositions
      Description:
      Sections:
          - Title: Header And Data
            Anchor: Composition Header
            Description: In blogs or article lists, it is common to see a metadata under the title.
            Since: 4.0.0
            HTML: |
                <div class="{{ts-header}}">The Virtual YouTuber group with bigger ambitions moves toward idolization</div>
                <div class="[[ts-meta]] is-secondary">
                    <a class="item" href="#!">Yami Odymel</a>
                    <a class="item" href="#!">14/02/2020</a>
                </div>
                <div class="{{ts-divider}} is-section"></div>
                <div class="{{ts-header}}">How to compress the game to less than 40 KB and still keep the level uniqueness?</div>
                <div class="[[ts-meta]] is-secondary">
                    <a class="item" href="#!">Yami Odymel</a>
                    <a class="item" href="#!">18/01/2022</a>
                </div>
