#=======================================================
# 標頭
# Header
#=======================================================

Title: 層疊排列
Description: 以上下垂直排列其子元素。

#=======================================================
# 設定
# Settings
#=======================================================

Type: Article

#=======================================================
# 基本樣式
# Definitions
#=======================================================

Example:
    HTML: |
        <div class="[[ts-stack]]">
            <div class="{{ts-text}}">使用者帳號</div>
            <div class="{{ts-input}}">
                <input type="text" />
            </div>
            <div class="{{ts-text}}">密碼</div>
            <div class="{{ts-input}}">
                <input type="password" />
            </div>
        </div>

Definitions:
    - Title: 內容
      Description:
      Sections:
          - Title: 欄位
            Anchor: Column
            Description:
            Since: 4.0.0
            HTML: |
                <div class="ts-box">
                    <div class="ts-stack" style="height: 200px">
                        <div class="[[column]]">
                            <div class="{{ts-content}}">
                                標頭
                            </div>
                        </div>
                        <div class="[[column]] is-fluid">
                            <div class="{{ts-content}}">
                                內容
                            </div>
                        </div>
                        <div class="[[column]]">
                            <div class="{{ts-content}}">
                                頁腳
                            </div>
                        </div>
                    </div>
                </div>

    - Title: 外觀
      Description:
      Sections:
          - Title: 間距尺寸
            Anchor: Sizes
            Description:
            Since: 4.0.0
            HTML: |
                <div class="ts-stack">
                    <div class="{{ts-text}}">使用者帳號</div>
                    <div class="{{ts-input}}">
                        <input type="text" />
                    </div>
                    <div class="{{ts-text}}">密碼</div>
                    <div class="{{ts-input}}">
                        <input type="password" />
                    </div>
                </div>
                <div class="ts-stack [[is-medium]]">
                    <div class="{{ts-text}}">使用者帳號</div>
                    <div class="{{ts-input}}">
                        <input type="text" />
                    </div>
                    <div class="{{ts-text}}">密碼</div>
                    <div class="{{ts-input}}">
                        <input type="password" />
                    </div>
                </div>
                <div class="ts-stack [[is-large]]">
                    <div class="{{ts-text}}">使用者帳號</div>
                    <div class="{{ts-input}}">
                        <input type="text" />
                    </div>
                    <div class="{{ts-text}}">密碼</div>
                    <div class="{{ts-input}}">
                        <input type="password" />
                    </div>
                </div>

          - Title: 無縫隙的
            Anchor: Gapless
            Description:
            Since: 4.0.0
            HTML: |
                <div class="ts-stack [[is-gapless]]">
                    <div class="{{ts-text}}">使用者帳號</div>
                    <div class="{{ts-input}}">
                        <input type="text" />
                    </div>
                    <div class="{{ts-text}}">密碼</div>
                    <div class="{{ts-input}}">
                        <input type="password" />
                    </div>
                </div>

          - Title: 流動的
            Anchor: Fluid
            Description:
            Since: 4.0.0
            HTML: |
                <div class="ts-box">
                    <div class="ts-stack" style="height: 200px">
                        <div class="column">
                            <div class="{{ts-content}}">
                                標頭
                            </div>
                        </div>
                        <div class="column [[is-fluid]]">
                            <div class="{{ts-content}}">
                                內容
                            </div>
                        </div>
                        <div class="column">
                            <div class="{{ts-content}}">
                                頁腳
                            </div>
                        </div>
                    </div>
                </div>
