ui:
    navigation:
        getting_started: 初入上手
        components: 元件樣式
        responsive: 響應式
        examples: 實際範例
        playground: 即時測試
    components_categories:
        elements: 一般元素
        collections: 聚合型
        modules: 模組
        layouts: 介面排版
    components:
        accordion: 可折疊內容
        appbar: 應用程式標題列
        bottom_sheet: 底部展出選單
        breadcrumb: 導覽標記
        button: 按鈕
        card: 卡片
        carousel: 幻燈片
        checkbox: 核取方塊
        comments: 留言
        container: 界限容器
        conversation: 對話
        dialog: 詢問情境
        dimmer: 淡化幕
        divider: 分隔線
        drawer: 側邊展出內容
        dropdown: 下拉式選單
        editable: 可編輯文字
        embed: 嵌入式物件
        emoji: 表情
        feed: 動態消息
        file: 檔案上傳
        flag: 國旗
        form: 表單
        gallery: 藝廊
        grid: 網格系統
        header: 標題
        icon: 圖示
        image: 圖片
        infoitems: 資訊項目
        input: 輸入欄位
        items: 項目
        label: 標籤
        layout: 排版系統
        list: 清單
        loader: 載入指示器
        masonry: 可折疊內容
        menu: 選單
        message: 訊息
        modal: 彈出式視窗
        pagination: 分頁導覽
        persona: 人物資訊
        placeholder: 預置元素
        popup: 提示內容
        progress: 進度狀態
        quote: 引言
        radio: 單選方塊
        rating: 評分
        search: 搜尋欄位
        segment: 片段
        select: 下拉式選單
        sidebar: 側邊欄
        slate: 矚目看板
        slider: 可滑動數值
        snackbar: 簡短通知
        statistic: 統計數據
        steps: 步驟
        table: 表格
        text: 文字
        timeline: 時間軸

components:
    - name: 一般元素
      tag: elements
      children:
          - name: 導覽標記
            tag: breadcrumb
          - name: 按鈕
            tag: button
          - name: 核取方塊
            tag: checkbox
          - name: 分隔線
            tag: divider
          - name: 表情
            tag: emoji
          - name: 檔案上傳
            tag: file
          - name: 國旗
            tag: flag
          - name: 標題
            tag: header
          - name: 圖示
            tag: icon
          - name: 圖片
            tag: image
          - name: 輸入欄位
            tag: input
          - name: 標籤
            tag: label
          - name: 選單
            tag: menu
          - name: 訊息
            tag: message
          - name: 分頁導覽
            tag: pagination
          - name: 人物資訊
            tag: persona
          - name: 預置元素
            tag: placeholder
          - name: 引言
            tag: quote
          - name: 單選方塊
            tag: radio
          - name: 片段
            tag: segment
          - name: 下拉式選單
            tag: select
          - name: 矚目看板
            tag: slate
          - name: 統計數據
            tag: statistic
          - name: 文字
            tag: text

    - name: 聚合型
      tag: collections
      children:
          - name: 卡片
            tag: card
          - name: 留言
            tag: comments
          - name: 對話
            tag: conversation
          - name: 動態消息
            tag: feed
          - name: 表單
            tag: form
          - name: 藝廊
            tag: gallery
          - name: 資訊項目
            tag: infoitems
          - name: 項目
            tag: items
          - name: 清單
            tag: list
          - name: 步驟
            tag: steps
          - name: 表格
            tag: table
          - name: 時間軸
            tag: timeline

    - name: 模組
      tag: modules
      children:
          - name: 可折疊內容
            tag: accordion
          - name: 底部展出選單
            tag: bottom-sheet
          - name: 幻燈片
            tag: carousel
          - name: 詢問情境
            tag: dialog
          - name: 淡化幕
            tag: dimmer
          - name: 側邊展出內容
            tag: drawer
          - name: 下拉式選單
            tag: dropdown
          - name: 可編輯文字
            tag: editable
          - name: 嵌入式物件
            tag: embed
          - name: 載入指示器
            tag: loader
          - name: 彈出式視窗
            tag: modal
          - name: 提示內容
            tag: popup
          - name: 進度狀態
            tag: progress
          - name: 評分
            tag: rating
          - name: 搜尋欄位
            tag: search
          - name: 可滑動數值
            tag: slider
          - name: 簡短通知
            tag: snackbar

    - name: 介面排版
      tag: layout
      children:
          - name: 應用程式標題列
            tag: appbar
          - name: 界限容器
            tag: container
          - name: 網格系統
            tag: grid
          - name: 排版系統
            tag: layout
          - name: 瀑布流版型
            tag: masonry
          - name: 側邊欄
            tag: sidebar
