ui:
    navigation:
        getting_started: 初入上手
        components: 元件樣式
        responsive: 響應式
        examples: 實際範例
        playground: 即時測試
        about: 關於
        back_to_top: 回到頂部
    components_categories:
        elements: 一般元素
        collections: 聚合型
        modules: 模組
        layouts: 介面排版
    components:
        accordion: 可折疊內容
        appbar: 應用程式標題列
        bottom_sheet: 底部展出選單
        breadcrumb: 導覽標記
        button: 按鈕
        card: 卡片
        carousel: 幻燈片
        checkbox: 核取方塊
        comments: 留言
        container: 界限容器
        conversation: 對話
        dialog: 詢問情境
        dimmer: 淡化幕
        divider: 分隔線
        drawer: 側邊展出內容
        dropdown: 下拉式選單
        editable: 可編輯文字
        embed: 嵌入式物件
        emoji: 表情
        feed: 動態消息
        file: 檔案上傳
        flag: 國旗
        form: 表單
        gallery: 藝廊
        grid: 網格系統
        header: 標題
        icon: 圖示
        image: 圖片
        infoitems: 資訊項目
        input: 輸入欄位
        items: 項目
        label: 標籤
        layout: 排版系統
        list: 清單
        loader: 載入指示器
        masonry: 可折疊內容
        menu: 選單
        message: 訊息
        modal: 彈出式視窗
        pagination: 分頁導覽
        persona: 人物資訊
        placeholder: 預置元素
        popup: 提示內容
        progress: 進度狀態
        quote: 引言
        radio: 單選方塊
        rating: 評分
        search: 搜尋欄位
        segment: 片段
        select: 下拉式選單
        sidebar: 側邊欄
        slate: 矚目看板
        slider: 可滑動數值
        snackbar: 簡短通知
        statistic: 統計數據
        steps: 步驟
        table: 表格
        text: 文字
        timeline: 時間軸

components:
    elements:
        - breadcrumb
        -button
          - checkbox
          - divider
          - emoji
          - file
          - flag
          - header
          - icon
          - image
          - input
          - label
          - menu
          - message
          - pagination
          - persona
          - placeholder
          - quote
          - radio
          - segment
          - select
          - slate
          - statistic
          - text

    collections:
            - card
            - comments
            - conversation
            - feed
            - form
            - gallery
            - infoitems
            - items
            - list
            - steps
            - table
            - timeline

    modules:
            - accordion
            - bottom-sheet
            - carousel
            - dialog
            - dimmer
            - drawer
            - dropdown
            - editable
            - embed
            - loader
            - modal
            - popup
            - progress
            - rating
            - search
            - slider
            - snackbar

    layouts:
            - appbar
            - container
            - grid
            - layout
            - masonry
            - sidebar
