#=======================================================
# Translation Information
#=======================================================

Information:
    Language: English (US)
    Path: en-us
    Flag: america
    Version: 4.0.0

#=======================================================
# Translation Contributors
#=======================================================

Contributors:
    - Name: Yami Odymel
      Website: https://twitter.com/YamiOdymel

#=======================================================
#
#
#=======================================================

UI:
    Paragraph:
        #=======================================================
        # Navbar
        #=======================================================

        Navbar_GettingStarted: Getting Started
        Navbar_Components: Components
        Navbar_Examples: Examples

        #=======================================================
        # Examples
        #=======================================================

        Example_WIP: WIP
        Example_WIP_Description: 由於元件正在持續新增，我們亦會不斷地更新範例頁面，請定時回來檢查更新。

        Example_DesignedForDesktop: NOTCIE
        Example_DesignedForDesktop_Description: These examples were made for the desktops; The layout may be distorted or cropped if viewed on a mobile device.

        #=======================================================
        # Index
        #=======================================================

        Index_Title: Tocas UI
        Index_Description: The fastest and most intuitive way to build diverse websites and progressive web application interfaces.
        Index_GettingStarted: Getting Started
        Index_Examples: Examples

        Index_ComingSoon: Coming Soon
        Index_ComingSoon_Description: Quickly build applications, shopping malls, interfaces with the Tocas Templates components library.

        Index_Donators: The project is sponsored by

        # Spotlight A
        Index_Spotlight_A_Title: No jQuery dependency.
        Index_Spotlight_A_Description: In addition to consuming excess network bandwidth; jQuery is no longer the best choice for modern websites. Tocas UI works well with all front-end frameworks.
        Index_Spotlight_B_Title: No need for npm or Webpack.
        Index_Spotlight_B_Description: "You don't need to install a bunch of packages via npm, nor setting up a bunch of loaders in Webpack. You just copy the HTML tags we provided and... TADA! It's that easy."
        Index_Spotlight_C_Title: Full documentation.
        Index_Spotlight_C_Description: Even if you haven't written Bootstrap or Bulma, Semantic UI, Material Design... you can still understand the whole interface system and how responsive design works with a complete explanation.
        Index_Spotlight_D_Title: The design is like a whole new generation.
        Index_Spotlight_D_Description: The existing components and styles are all available and ready for you.

        # Showcases
        Index_Showcase_ImageCard_Section: Image Cards
        Index_Showcase_ImageCard_Title: Delicious thousand-layer cake!
        Index_Showcase_ImageCard_Content: If you order online through May, you will now receive a limited number of free eco bags.
        Index_Showcase_Button_Section: Button
        Index_Showcase_Button_A: Submit
        Index_Showcase_Button_B: Cancel
        Index_Showcase_Button_C: Delete
        Index_Showcase_Label_Section: Label
        Index_Showcase_Label_A: Asuka Minato
        Index_Showcase_Label_B: Saionji Kazari
        Index_Showcase_Statistic_Section: Statistic
        Index_Showcase_Statistic_A_Label: Number of visits
        Index_Showcase_Statistic_B_Label: Total members
        Index_Showcase_Navbar_Section: Navbar
        Index_Showcase_Navbar_A: Users
        Index_Showcase_Navbar_B: Home
        Index_Showcase_Navbar_C: News
        Index_Showcase_Table_Section: Table
        Index_Showcase_Table_Header_A: 名稱
        Index_Showcase_Table_Header_B: 英文名稱
        Index_Showcase_Table_A_Cell_A: 半音商業銀行
        Index_Showcase_Table_A_Cell_B: Flat Bank
        Index_Showcase_Table_B_Cell_A: 對空音商事有限公司
        Index_Showcase_Table_B_Cell_B: Sorae & Co., Ltd.
        Index_Showcase_Table_C_Cell_A: 卡莉絲伊繁星
        Index_Showcase_Table_C_Cell_B: Caris Events
        Index_Showcase_Table_Footer: 統計筆數：3
        Index_Showcase_Breadcrumb_Section: Breadcrumb
        Index_Showcase_Breadcrumb_A: Movice
        Index_Showcase_Breadcrumb_B: Sci-Fi
        Index_Showcase_Breadcrumb_C: Interstellar
        Index_Showcase_Placeholder_Section: Placeholder
        Index_Showcase_Flag_Section: Flag
        Index_Showcase_Rating_Section: Rating
        Index_Showcase_Selection_Section: Selection
        Index_Showcase_Selection_A: Eco
        Index_Showcase_Selection_B: Balance
        Index_Showcase_Selection_C: Performance

        # Features
        Index_Feature_A_Title: 明暗主題與響應式設計
        Index_Feature_A_Description: 支援暗黑模式且有針對行動裝置所設計的介面密度樣式。
        Index_Feature_A_Action: See More
        Index_Feature_B_Title: 鬆離耦合性
        Index_Feature_B_Description: Tocas UI 元件以原子化設計令其能夠相互組合使用。
        Index_Feature_B_Action: View Components
        Index_Feature_C_Title: 臨機應變
        Index_Feature_C_Description: 想做電商平臺？沒問題。管理介面？沒問題。社群網站？沒問題。
        Index_Feature_C_Action: View Examples

        # Let's Go
        Index_LetsGo_Title: Ready?
        Index_LetsGo_Description: Copy the following HTML tags to your web page and have a blast.
        Index_LetsGo_Code: >
            <!-- Tocas UI：CSS 與元件 -->
            <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/tocas-ui/4.0.0/tocas.min.css">

            <!-- Tocas JS：模塊與 JavaScript 函式 -->
            <script src="https://cdnjs.cloudflare.com/ajax/libs/tocas-ui/4.0.0/tocas.min.js"></script>

        Index_LetsGo_Action: Getting Started

        #=======================================================
        # Footer
        #=======================================================
        Footer_ToTop: Back to Top
        Footer_GettingStarted: Getting Started
        Footer_Components: Components
        Footer_Examples: Examples
        Footer_Paragraph: Designed by <a href="https://twitter.com/YamiOdymel" target="_blank">Yami Odymel</a> from <span class="ts-flag is-taiwan-flag is-small"></span> Taiwan with the love of the <a href="https://github.com/teacat/tocas/graphs/contributors" target="_blank">contributors</a> ❤️. The source code is licensed under <a href="https://github.com/teacat/tocas/blob/master/LICENSE" target="_blank">MIT</a> and the documents are <a href="https://creativecommons.org/publicdomain/zero/1.0/deed.zh_TW" target="_blank">CC 0</a> public domain. Tocas UI is a design language of <a href="https://caris.events" target="_blank">Caris Events</a>, which is owned by <a href="https://sorae.co/en-us.html" target="_blank">Sorae & Co.</a>
        Footer_Translators: "Localization translators: %s"

        #=======================================================
        # Article
        #=======================================================

        Article_Example_Title: Example
        Article_Schemes_Title: Theme
        Article_Schemes_User: Default
        Article_Schemes_Light: Light
        Article_Schemes_Dark: Dark
        Article_Scaling_Title: Scale
        Article_Scaling_Standard: Medium
        Article_Scaling_Large: Large
        Article_Scaling_Small: Small
        Article_Introduction: Introduction
        Article_Flag_Alias: Alias
        Article_SourceCode: Code
        Article_LookingFor_Title: Looking for similar components?
        Article_ToTop: Back to Top

        #=======================================================
        # Other
        #=======================================================

        TranslatorSeperator: ", "

    ComponentsCategories:
        Introduction: Introduction
        Layout: Layout
        Form: Forms
        Paragraphy: Typography
        Feedback: Feedback
        Media: Media
        Data: Data
        Navigation: Navigation
        Application: Application
        Others: Others

    Components:
        GettingStarted: Getting Started
        Colors: Colors
        Responsive: Responsive
        About: About
        Box: Box
        Center: Center
        Container: Container
        Content: Content
        Control: Control
        Grid: Grid
        Space: Space
        Row: Row
        Wrap: Wrap
        Button: Button
        Checkbox: Checkbox
        Combo: Combo
        Fieldset: Fieldset
        File: File
        Input: Input
        Radio: Radio
        Select: Select
        Selection: Selection
        Switch: Switch
        Divider: Divider
        Header: Header
        Mask: Mask
        Quote: Quote
        Segment: Segment
        Text: Text
        Gauge: Gauge
        Loading: Loading
        Modal: Modal
        Notice: Notice
        Placeholder: Placeholder
        Procedure: Procedure
        Progress: Progress
        Snackbar: Snackbar
        Avatar: Avatar
        Flag: Flag
        Icon: Icon
        Iconset: Iconset
        Image: Image
        Imageset: Imageset
        Accordion: Accordion
        Badge: Badge
        Checklist: Checklist
        Chip: Chip
        Close: Close
        Conversation: Conversation
        List: List
        Meta: Meta
        Rating: Rating
        Statistic: Statistic
        Table: Table
        Breadcrumb: Breadcrumb
        Menu: Menu
        Pagination: Pagination
        Tab: Tab
        AppDialog: AppDialog
        AppLayout: App Layout
        AppModal: App Modal
        AppNavbar: App Navbar
        AppSidebar: App Sidebar
        Comment: Comment

Components:
    - Name: Introduction
      Items:
          - GettingStarted
          - Colors
          - Responsive
          #- About
    - Name: Layout
      Items:
          - Box
          - Center
          - Container
          - Content
          - Control
          - Grid
          - Space
          - Row
          - Wrap
    - Name: Form
      Items:
          - Button
          - Checkbox
          # - Combo
          - Fieldset
          - File
          - Input
          - Radio
          - Select
          - Selection
          - Switch
    - Name: Paragraphy
      Items:
          - Divider
          - Header
          - Mask
          - Quote
          - Segment
          - Text
    - Name: Feedback
      Items:
          - Gauge
          - Loading
          - Modal
          - Notice
          - Placeholder
          - Procedure
          - Progress
          - Snackbar
    - Name: Media
      Items:
          - Avatar
          - Flag
          - Icon
          - Iconset
          - Image
          - Imageset
    - Name: Data
      Items:
          - Accordion
          - Badge
          - Checklist
          - Chip
          - Close
          - Conversation
          - List
          - Meta
          - Rating
          - Statistic
          - Table
    - Name: Navigation
      Items:
          - Breadcrumb
          - Menu
          - Pagination
          - Tab
    - Name: Application
      Items:
          - AppLayout
          - AppNavbar
          - AppSidebar
