#=======================================================
# Translation Information
#=======================================================

Information:
    Language: 台灣正體
    Path: zh-tw
    Flag: taiwan
    Version: 4.0.0

#=======================================================
# Translation Contributors
#=======================================================

Contributors:
    - Name: Yami Odymel
      Website: https://yami.io/
    - Name: coin3x
      Website:
    - Name: Sea-n
      Website: https://www.sean.taipei/

#=======================================================
#
#
#=======================================================

UI:
    Paragraph:
        Footer: 由來自 <span class="ts-flag is-taiwan-flag"></span> 台灣的 <a href="https://yami.io" target="_blank">Yami Odymel</a> 所設計，當然還有<a href="https://github.com/teacat/tocas/graphs/contributors" target="_blank">貢獻者們</a>的愛心❤️。原始碼授權方式為 <a href="https://github.com/teacat/tocas/blob/master/LICENSE" target="_blank">MIT</a>，文件則為 <a href="https://creativecommons.org/publicdomain/zero/1.0/deed.zh_TW" target="_blank">CC 0</a> 公眾領域。還請盡情地使用、分享或一同改進。Tocas UI 是<a href="https://caris.events" target="_blank">卡莉絲伊繁星</a>的開發工具，而卡莉絲伊繁星屬<a href="https://sorae.co" target="_blank">對空音商事有限公司</a>。
        Translators: 台灣正體語系協作者：%s
        TranslatorSeperator: 、
        Code: >
            <!-- Tocas UI：CSS 與元件 -->
            <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/tocas-ui/2.3.3/tocas.css">
            <!-- Tocas JS：模塊與 JavaScript 函式 -->
            <script src="https://cdnjs.cloudflare.com/ajax/libs/tocas-ui/2.3.3/tocas.js"></script>
    Navigation:
        GettingStarted: 初入上手
        Introduction: 開始使用
        Components: 元件樣式
        Responsive: 響應式
        Examples: 實際範例
        Playground: 即時測試
        About: 關於
        BackToTop: 回到頂部
        Emphasises: 顏色與語意

    ComponentsCategories:
        Layout: 格局設計
        Form: 表單
        Paragraphy: 文字與段落
        Feedback: 視覺回饋
        Media: 多媒體與圖示
        Data: 資料顯示
        Navigation: 導覽
        Application: 應用程式
        Others: 其他

    Components:
        Box: 箱型容器
        Center: 絕對置中
        Container: 界限容器
        Content: 內容區塊
        Grid: 網格系統
        Space: 空白間隔
        Row: 水平排列
        Wrap: 間隔容器
        Button: 按鈕
        Checkbox: 核取方塊
        Combo: 複合式下拉選擇
        Fieldset: 欄位分組
        File: 檔案上傳
        Input: 輸入欄位
        Radio: 選項按鈕
        Select: 下拉式選擇
        Selection: 項目切換
        Switch: 指撥開關
        Divider: 分隔線
        Header: 標題
        Mask: 內容遮罩
        Quote: 引言
        Segment: 片段
        Text: 文字
        Typography: 敘述段落
        Empty: 無內容狀態
        Loading: 讀取狀態
        Notice: 提示訊息
        Placeholder: 預置內容
        Progress: 進度條
        Slate: 概要看板
        Snackbar: 簡短通知
        Steps: 步驟指示器
        Avatar: 大頭貼
        Flag: 國家旗幟
        Icon: 圖示
        Image: 多媒體圖片
        Badge: 計數徽章
        Chip: 關聯標籤
        Close: 關閉按鈕
        List: 清單
        Meta: 中繼資料
        Rating: 評分
        Statistic: 統計數據
        Table: 表格
        Breadcrumb: 導覽標記
        Pagination: 頁數導覽列
        Tab: 分頁籤
        Dialog: 對話視窗
        Layout: 格局劃分
        Modal: 模態視窗
        Navbar: 導航列
        Sidebar: 側邊欄
        Accordion: 可折疊內容
        Comment: 留言
        Form: 表單
        OpenGraph: OG

Components:
    Layout:
        - Box
        - Center
        - Container
        - Content
        - Grid
        - Space
        - Row
        - Wrap
    Form:
        - Button
        - Checkbox
        - Combo
        - Fieldset
        - File
        - Input
        - Radio
        - Select
        - Selection
        - Switch
    Paragraphy:
        - Divider
        - Header
        - Mask
        - Quote
        - Segment
        - Text
        - Typography
    Feedback:
        - Empty
        - Loading
        - Notice
        - Placeholder
        - Progress
        - Slate
        - Snackbar
        - Steps
    Media:
        - Avatar
        - Flag
        - Icon
        - Image
    Data:
        - Badge
        - Chip
        - Close
        - List
        - Meta
        - Rating
        - Statistic
        - Table
    Navigation:
        - Breadcrumb
        - Pagination
        - Tab
    Application:
        - Layout
        - Navbar
        - Sidebar
    Others:
        - Accordion
        - Comment
        - Form
        - OpenGraph
