#=======================================================
# Translation Information
#=======================================================

Information:
    Language: 台灣正體
    Path: zh-tw
    Flag: taiwan
    Version: 4.0.0

#=======================================================
# Translation Contributors
#=======================================================

Contributors:
    - Name: Yami Odymel
      Website: https://yami.io/
    - Name: coin3x
      Website:
    - Name: Sea-n
      Website: https://www.sean.taipei/

#=======================================================
#
#
#=======================================================

UI:
    Paragraph:
        Footer: 由來自 <span class="ts-flag is-taiwan-flag"></span> 台灣的 <a href="https://yami.io" target="_blank">Yami Odymel</a> 所設計，當然還有<a href="https://github.com/teacat/tocas/graphs/contributors" target="_blank">貢獻者們</a>的愛心❤️。原始碼授權方式為 <a href="https://github.com/teacat/tocas/blob/master/LICENSE" target="_blank">MIT</a>，文件則為 <a href="https://creativecommons.org/publicdomain/zero/1.0/deed.zh_TW" target="_blank">CC 0</a> 公眾領域。還請盡情地使用、分享或一同改進。Tocas UI 是<a href="https://caris.events" target="_blank">卡莉絲伊繁星</a>的開發工具，而卡莉絲伊繁星屬<a href="https://sorae.co" target="_blank">對空音商事有限公司</a>。
        Translators: 台灣正體語系協作者：%s
        TranslatorSeperator: 、
        Code: >
            <!-- Tocas UI：CSS 與元件 -->
            <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/tocas-ui/2.3.3/tocas.css">
            <!-- Tocas JS：模塊與 JavaScript 函式 -->
            <script src="https://cdnjs.cloudflare.com/ajax/libs/tocas-ui/2.3.3/tocas.js"></script>
    Navigation:
        GettingStarted: 初入上手
        Introduction: 開始使用
        Components: 元件樣式
        Responsive: 響應式
        Examples: 實際範例
        Playground: 即時測試
        About: 關於
        BackToTop: 回到頂部
        Emphasises: 顏色與語意

    ComponentsCategories:
        Elements: 一般元素
        Collections: 聚合型
        Modules: 模組
        Layouts: 介面排版

    Components:
        Box: 箱型容器
        Bullseye: 置中靶心
        Container: 界限容器
        Content: 內容區塊
        Grid: 網格系統
        Layout: 格局柵欄
        Stack: 垂直排列
        Space: 空白間隔
        Row: 水平排列
        Navbar: 導航列
        Sidebar: 側邊欄
        Accordion: 可折疊內容
        Badge: 計數徽章
        Breadcrumb: 導覽標記
        Button: 按鈕
        Checkbox: 核取方塊
        Chip: 關聯選項
        Choice: 選擇項目
        Close: 關閉
        Divider: 分隔線
        Empty: 無內容狀態
        Fieldset: 欄位群組
        File: 檔案欄位
        Icon: 圖示
        Image: 圖片
        Input: 輸入欄位
        List: 清單
        Meta: 中繼資料
        Notice: 提示訊息
        Pagination: 頁數導覽列
        Placeholder: 預置內容
        Progress: 進度指示列
        Radio: 單選方塊
        Rating: 評分
        Reaction: 表情反應
        Segment: 敘述片段
        Select: 下拉選擇欄位
        Slate: 概要看板
        Snackbar: 簡短通知
        Statistic: 統計數據
        Steps: 步驟指示器
        Switch: 指撥開關
        Tab: 分頁籤
        Table: 表格
        Text: 文字

Components:
    Elements:
        - Badge
        - Breadcrumb
        - Button
        - Capacity
        - Checkbox
        - Divider
        - Emoji
        - File
        - Flag
        - Header
        - Icon
        - Image
        - Input
        - Label
        - Menu
        - Message
        - Pagination
        - Persona
        - Placeholder
        - Quote
        - Radio
        - Segment
        - Select
        - Slate
        - Statistic
        - Text

    Collections:
        - Card
        - Comments
        - Conversation
        - Feed
        - Form
        - Gallery
        - Infoitems
        - Items
        - List
        - Steps
        - Table
        - Timeline

    Modules:
        - Accordion
        - Bottom Sheet
        - Carousel
        - Dialog
        - Dimmer
        - Drawer
        - Dropdown
        - Editable
        - Embed
        - Loader
        - Modal
        - Popup
        - Progress
        - Rating
        - Search
        - Slider
        - Snackbar

    Layouts:
        - Appbar
        - Container
        - Grid
        - Layout
        - Masonry
        - Sidebar
        - Space
